var shift = [{
    scheduleDay: 1,
    scheduleDayOfWeek: 1,
    scheduleDayOfMonth: 0,
    scheduleNthDayOfMonth: "",
    scheduleCareId: 0,
    scheduleShift: "",
    scheduleTimes: "",
    scheduleClient: "",
    day: "",
    scheduleCarerName: "",
    scheduleEmployeeNumber: "",
    scheduleShiftNumber: -1
  },
  {
    scheduleDay: 2,
    scheduleDayOfWeek: 2,
    scheduleDayOfMonth: 0,
    scheduleNthDayOfMonth: "",
    scheduleCareId: 0,
    scheduleShift: "",
    scheduleTimes: "",
    scheduleClient: "",
    day: "",
    scheduleCarerName: "",
    scheduleEmployeeNumber: "",
    scheduleShiftNumber: -1
  },
  {
    scheduleDay: 3,
    scheduleDayOfWeek: 3,
    scheduleDayOfMonth: 0,
    scheduleNthDayOfMonth: "",
    scheduleCareId: 0,
    scheduleShift: "",
    scheduleTimes: "",
    scheduleClient: "",
    day: "",
    scheduleCarerName: "",
    scheduleEmployeeNumber: "",
    scheduleShiftNumber: -1
  },
  {
    scheduleDay: 4,
    scheduleDayOfWeek: 4,
    scheduleDayOfMonth: 0,
    scheduleNthDayOfMonth: "",
    scheduleCareId: 0,
    scheduleShift: "",
    scheduleTimes: "",
    scheduleClient: "",
    day: "",
    scheduleCarerName: "",
    scheduleEmployeeNumber: "",
    scheduleShiftNumber: -1
  },
  {
    scheduleDay: 5,
    scheduleDayOfWeek: 5,
    scheduleDayOfMonth: 0,
    scheduleNthDayOfMonth: "",
    scheduleCareId: 0,
    scheduleShift: "",
    scheduleTimes: "",
    scheduleClient: "",
    day: "",
    scheduleCarerName: "",
    scheduleEmployeeNumber: "",
    scheduleShiftNumber: -1
  },
  {
    scheduleDay: 6,
    scheduleDayOfWeek: 6,
    scheduleDayOfMonth: 0,
    scheduleNthDayOfMonth: "",
    scheduleCareId: 0,
    scheduleShift: "",
    scheduleTimes: "",
    scheduleClient: "",
    day: "",
    scheduleCarerName: "",
    scheduleEmployeeNumber: "",
    scheduleShiftNumber: -1
  },
  {
    scheduleDay: 7,
    scheduleDayOfWeek: 7,
    scheduleDayOfMonth: 0,
    scheduleNthDayOfMonth: "",
    scheduleCareId: 0,
    scheduleShift: "",
    scheduleTimes: "",
    scheduleClient: "",
    day: "",
    scheduleCarerName: "",
    scheduleEmployeeNumber: "",
    scheduleShiftNumber: -1
  },
  {
    scheduleDay: 8,
    scheduleDayOfWeek: 1,
    scheduleDayOfMonth: 0,
    scheduleNthDayOfMonth: "",
    scheduleCareId: 0,
    scheduleShift: "",
    scheduleTimes: "",
    scheduleClient: "",
    day: "",
    scheduleCarerName: "",
    scheduleEmployeeNumber: "",
    scheduleShiftNumber: -1
  },
  {
    scheduleDay: 9,
    scheduleDayOfWeek: 2,
    scheduleDayOfMonth: 0,
    scheduleNthDayOfMonth: "",
    scheduleCareId: 0,
    scheduleShift: "",
    scheduleTimes: "",
    scheduleClient: "",
    day: "",
    scheduleCarerName: "",
    scheduleEmployeeNumber: "",
    scheduleShiftNumber: -1
  },
  {
    scheduleDay: 10,
    scheduleDayOfWeek: 3,
    scheduleDayOfMonth: 0,
    scheduleNthDayOfMonth: "",
    scheduleCareId: 0,
    scheduleShift: "",
    scheduleTimes: "",
    scheduleClient: "",
    day: "",
    scheduleCarerName: "",
    scheduleEmployeeNumber: "",
    scheduleShiftNumber: -1
  },
  {
    scheduleDay: 11,
    scheduleDayOfWeek: 4,
    scheduleDayOfMonth: 0,
    scheduleNthDayOfMonth: "",
    scheduleCareId: 0,
    scheduleShift: "",
    scheduleTimes: "",
    scheduleClient: "",
    day: "",
    scheduleCarerName: "",
    scheduleEmployeeNumber: "",
    scheduleShiftNumber: -1
  },
  {
    scheduleDay: 12,
    scheduleDayOfWeek: 5,
    scheduleDayOfMonth: 0,
    scheduleNthDayOfMonth: "",
    scheduleCareId: 0,
    scheduleShift: "",
    scheduleTimes: "",
    scheduleClient: "",
    day: "",
    scheduleCarerName: "",
    scheduleEmployeeNumber: "",
    scheduleShiftNumber: -1
  },
  {
    scheduleDay: 13,
    scheduleDayOfWeek: 6,
    scheduleDayOfMonth: 0,
    scheduleNthDayOfMonth: "",
    scheduleCareId: 0,
    scheduleShift: "",
    scheduleTimes: "",
    scheduleClient: "",
    day: "",
    scheduleCarerName: "",
    scheduleEmployeeNumber: "",
    scheduleShiftNumber: -1
  },
  {
    scheduleDay: 14,
    scheduleDayOfWeek: 7,
    scheduleDayOfMonth: 0,
    scheduleNthDayOfMonth: "",
    scheduleCareId: 0,
    scheduleShift: "",
    scheduleTimes: "",
    scheduleClient: "",
    day: "",
    scheduleCarerName: "",
    scheduleEmployeeNumber: "",
    scheduleShiftNumber: -1
  },
  {
    scheduleDay: 15,
    scheduleDayOfWeek: 1,
    scheduleDayOfMonth: 0,
    scheduleNthDayOfMonth: "",
    scheduleCareId: 0,
    scheduleShift: "",
    scheduleTimes: "",
    scheduleClient: "",
    day: "",
    scheduleCarerName: "",
    scheduleEmployeeNumber: "",
    scheduleShiftNumber: -1
  },
  {
    scheduleDay: 16,
    scheduleDayOfWeek: 2,
    scheduleDayOfMonth: 0,
    scheduleNthDayOfMonth: "",
    scheduleCareId: 0,
    scheduleShift: "",
    scheduleTimes: "",
    scheduleClient: "",
    day: "",
    scheduleCarerName: "",
    scheduleEmployeeNumber: "",
    scheduleShiftNumber: -1
  },
  {
    scheduleDay: 17,
    scheduleDayOfWeek: 3,
    scheduleDayOfMonth: 0,
    scheduleNthDayOfMonth: "",
    scheduleCareId: 0,
    scheduleShift: "",
    scheduleTimes: "",
    scheduleClient: "",
    day: "",
    scheduleCarerName: "",
    scheduleEmployeeNumber: "",
    scheduleShiftNumber: -1
  },
  {
    scheduleDay: 18,
    scheduleDayOfWeek: 4,
    scheduleDayOfMonth: 0,
    scheduleNthDayOfMonth: "",
    scheduleCareId: 0,
    scheduleShift: "",
    scheduleTimes: "",
    scheduleClient: "",
    day: "",
    scheduleCarerName: "",
    scheduleEmployeeNumber: "",
    scheduleShiftNumber: -1
  },
  {
    scheduleDay: 19,
    scheduleDayOfWeek: 5,
    scheduleDayOfMonth: 0,
    scheduleNthDayOfMonth: "",
    scheduleCareId: 0,
    scheduleShift: "",
    scheduleTimes: "",
    scheduleClient: "",
    day: "",
    scheduleCarerName: "",
    scheduleEmployeeNumber: "",
    scheduleShiftNumber: -1
  },
  {
    scheduleDay: 20,
    scheduleDayOfWeek: 6,
    scheduleDayOfMonth: 0,
    scheduleNthDayOfMonth: "",
    scheduleCareId: 0,
    scheduleShift: "",
    scheduleTimes: "",
    scheduleClient: "",
    day: "",
    scheduleCarerName: "",
    scheduleEmployeeNumber: "",
    scheduleShiftNumber: -1
  },
  {
    scheduleDay: 21,
    scheduleDayOfWeek: 7,
    scheduleDayOfMonth: 0,
    scheduleNthDayOfMonth: "",
    scheduleCareId: 0,
    scheduleShift: "",
    scheduleTimes: "",
    scheduleClient: "",
    day: "",
    scheduleCarerName: "",
    scheduleEmployeeNumber: "",
    scheduleShiftNumber: -1
  },
  {
    scheduleDay: 22,
    scheduleDayOfWeek: 1,
    scheduleDayOfMonth: 0,
    scheduleNthDayOfMonth: "",
    scheduleCareId: 0,
    scheduleShift: "",
    scheduleTimes: "",
    scheduleClient: "",
    day: "",
    scheduleCarerName: "",
    scheduleEmployeeNumber: "",
    scheduleShiftNumber: -1
  },
  {
    scheduleDay: 23,
    scheduleDayOfWeek: 2,
    scheduleDayOfMonth: 0,
    scheduleNthDayOfMonth: "",
    scheduleCareId: 0,
    scheduleShift: "",
    scheduleTimes: "",
    scheduleClient: "",
    day: "",
    scheduleCarerName: "",
    scheduleEmployeeNumber: "",
    scheduleShiftNumber: -1
  },
  {
    scheduleDay: 24,
    scheduleDayOfWeek: 3,
    scheduleDayOfMonth: 0,
    scheduleNthDayOfMonth: "",
    scheduleCareId: 0,
    scheduleShift: "",
    scheduleTimes: "",
    scheduleClient: "",
    day: "",
    scheduleCarerName: "",
    scheduleEmployeeNumber: "",
    scheduleShiftNumber: -1
  },
  {
    scheduleDay: 25,
    scheduleDayOfWeek: 4,
    scheduleDayOfMonth: 0,
    scheduleNthDayOfMonth: "",
    scheduleCareId: 0,
    scheduleShift: "",
    scheduleTimes: "",
    scheduleClient: "",
    day: "",
    scheduleCarerName: "",
    scheduleEmployeeNumber: "",
    scheduleShiftNumber: -1
  },
  {
    scheduleDay: 26,
    scheduleDayOfWeek: 5,
    scheduleDayOfMonth: 0,
    scheduleNthDayOfMonth: "",
    scheduleCareId: 0,
    scheduleShift: "",
    scheduleTimes: "",
    scheduleClient: "",
    day: "",
    scheduleCarerName: "",
    scheduleEmployeeNumber: "",
    scheduleShiftNumber: -1
  },
  {
    scheduleDay: 27,
    scheduleDayOfWeek: 6,
    scheduleDayOfMonth: 0,
    scheduleNthDayOfMonth: "",
    scheduleCareId: 0,
    scheduleShift: "",
    scheduleTimes: "",
    scheduleClient: "",
    day: "",
    scheduleCarerName: "",
    scheduleEmployeeNumber: "",
    scheduleShiftNumber: -1
  },
  {
    scheduleDay: 28,
    scheduleDayOfWeek: 7,
    scheduleDayOfMonth: 0,
    scheduleNthDayOfMonth: "",
    scheduleCareId: 0,
    scheduleShift: "",
    scheduleTimes: "",
    scheduleClient: "",
    day: "",
    scheduleCarerName: "",
    scheduleEmployeeNumber: "",
    scheduleShiftNumber: -1
  },
  {
    scheduleDay: 29,
    scheduleDayOfWeek: 1,
    scheduleDayOfMonth: 0,
    scheduleNthDayOfMonth: "",
    scheduleCareId: 0,
    scheduleShift: "",
    scheduleTimes: "",
    scheduleClient: "",
    day: "",
    scheduleCarerName: "",
    scheduleEmployeeNumber: "",
    scheduleShiftNumber: -1
  },
  {
    scheduleDay: 30,
    scheduleDayOfWeek: 2,
    scheduleDayOfMonth: 0,
    scheduleNthDayOfMonth: "",
    scheduleCareId: 0,
    scheduleShift: "",
    scheduleTimes: "",
    scheduleClient: "",
    day: "",
    scheduleCarerName: "",
    scheduleEmployeeNumber: "",
    scheduleShiftNumber: -1
  },
  {
    scheduleDay: 31,
    scheduleDayOfWeek: 3,
    scheduleDayOfMonth: 0,
    scheduleNthDayOfMonth: "",
    scheduleCareId: 0,
    scheduleShift: "",
    scheduleTimes: "",
    scheduleClient: "",
    day: "",
    scheduleCarerName: "",
    scheduleEmployeeNumber: "",
    scheduleShiftNumber: -1
  },
  {
    scheduleDay: 32,
    scheduleDayOfWeek: 4,
    scheduleDayOfMonth: 0,
    scheduleNthDayOfMonth: "",
    scheduleCareId: 0,
    scheduleShift: "",
    scheduleTimes: "",
    scheduleClient: "",
    day: "",
    scheduleCarerName: "",
    scheduleEmployeeNumber: "",
    scheduleShiftNumber: -1
  },
  {
    scheduleDay: 33,
    scheduleDayOfWeek: 5,
    scheduleDayOfMonth: 0,
    scheduleNthDayOfMonth: "",
    scheduleCareId: 0,
    scheduleShift: "",
    scheduleTimes: "",
    scheduleClient: "",
    day: "",
    scheduleCarerName: "",
    scheduleEmployeeNumber: "",
    scheduleShiftNumber: -1
  },
  {
    scheduleDay: 34,
    scheduleDayOfWeek: 6,
    scheduleDayOfMonth: 0,
    scheduleNthDayOfMonth: "",
    scheduleCareId: 0,
    scheduleShift: "",
    scheduleTimes: "",
    scheduleClient: "",
    day: "",
    scheduleCarerName: "",
    scheduleEmployeeNumber: "",
    scheduleShiftNumber: -1
  },
  {
    scheduleDay: 35,
    scheduleDayOfWeek: 7,
    scheduleDayOfMonth: 0,
    scheduleNthDayOfMonth: "",
    scheduleCareId: 0,
    scheduleShift: "",
    scheduleTimes: "",
    scheduleClient: "",
    day: "",
    scheduleCarerName: "",
    scheduleEmployeeNumber: "",
    scheduleShiftNumber: -1
  },
  {
    scheduleDay: 36,
    scheduleDayOfWeek: 1,
    scheduleDayOfMonth: 0,
    scheduleNthDayOfMonth: "",
    scheduleCareId: 0,
    scheduleShift: "",
    scheduleTimes: "",
    scheduleClient: "",
    day: "",
    scheduleCarerName: "",
    scheduleEmployeeNumber: "",
    scheduleShiftNumber: -1
  },
  {
    scheduleDay: 37,
    scheduleDayOfWeek: 2,
    scheduleDayOfMonth: 0,
    scheduleNthDayOfMonth: "",
    scheduleCareId: 0,
    scheduleShift: "",
    scheduleTimes: "",
    scheduleClient: "",
    day: "",
    scheduleCarerName: "",
    scheduleEmployeeNumber: "",
    scheduleShiftNumber: -1
  },
  {
    scheduleDay: 38,
    scheduleDayOfWeek: 3,
    scheduleDayOfMonth: 0,
    scheduleNthDayOfMonth: "",
    scheduleCareId: 0,
    scheduleShift: "",
    scheduleTimes: "",
    scheduleClient: "",
    day: "",
    scheduleCarerName: "",
    scheduleEmployeeNumber: "",
    scheduleShiftNumber: -1
  },
  {
    scheduleDay: 39,
    scheduleDayOfWeek: 4,
    scheduleDayOfMonth: 0,
    scheduleNthDayOfMonth: "",
    scheduleCareId: 0,
    scheduleShift: "",
    scheduleTimes: "",
    scheduleClient: "",
    day: "",
    scheduleCarerName: "",
    scheduleEmployeeNumber: "",
    scheduleShiftNumber: -1
  },
  {
    scheduleDay: 40,
    scheduleDayOfWeek: 5,
    scheduleDayOfMonth: 0,
    scheduleNthDayOfMonth: "",
    scheduleCareId: 0,
    scheduleShift: "",
    scheduleTimes: "",
    scheduleClient: "",
    day: "",
    scheduleCarerName: "",
    scheduleEmployeeNumber: "",
    scheduleShiftNumber: -1
  },
  {
    scheduleDay: 41,
    scheduleDayOfWeek: 6,
    scheduleDayOfMonth: 0,
    scheduleNthDayOfMonth: "",
    scheduleCareId: 0,
    scheduleShift: "",
    scheduleTimes: "",
    scheduleClient: "",
    day: "",
    scheduleCarerName: "",
    scheduleEmployeeNumber: "",
    scheduleShiftNumber: -1
  },
  {
    scheduleDay: 42,
    scheduleDayOfWeek: 7,
    scheduleDayOfMonth: 0,
    scheduleNthDayOfMonth: "",
    scheduleCareId: 0,
    scheduleShift: "",
    scheduleTimes: "",
    scheduleClient: "",
    day: "",
    scheduleCarerName: "",
    scheduleEmployeeNumber: "",
    scheduleShiftNumber: -1
  }
];

module.exports.shift = shift;

